"""
Django settings for intranet project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS', default=[])

# Base para armar URLs absolutas fuera de una request (ej. el link que
# va dentro del QR de verificación en los PDF institucionales).
SITE_URL = env.str('DJANGO_SITE_URL', default='http://localhost:8000')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'directorio',
    'comunicados',
    'rrhh',
    'axes',
]

AUTH_USER_MODEL = 'usuarios.Usuario'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware.ForzarCambioPasswordMiddleware',
    'axes.middleware.AxesMiddleware',
]

# django-axes: bloqueo por fuerza bruta en el login.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 0.5  # horas (30 minutos)

ROOT_URLCONF = 'intranet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'rrhh.context_processors.flags_rrhh',
                'intranet.context_processors.barra_lateral',
            ],
        },
    },
]

WSGI_APPLICATION = 'intranet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# En Vercel no hay Postgres local: se usa la integración de base de datos
# (Neon), que inyecta DATABASE_URL automáticamente. En desarrollo local,
# sin esa variable, se sigue usando el Postgres propio vía DB_*.
if env.str('DATABASE_URL', default=''):
    DATABASES = {'default': env.db('DATABASE_URL')}
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['sslmode'] = 'require'
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST', default='localhost'),
            'PORT': env('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Requerido para que Vercel corra collectstatic automáticamente en el build.
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Almacenamiento de archivos subidos (comprobantes de firma, PDF de
# permisos, licencias médicas, liquidaciones, etc). En Vercel el
# filesystem es de solo lectura y no persiste entre invocaciones, así que
# ahí se usa Vercel Blob en vez de disco local. Se activa solo si existe
# BLOB_READ_WRITE_TOKEN (variable que agrega Vercel al crear el Blob
# store); en desarrollo local, sin ese token, se sigue usando el disco.
STORAGES = {
    'default': {
        'BACKEND': (
            'intranet.storage.VercelBlobStorage'
            if env.str('BLOB_READ_WRITE_TOKEN', default='')
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Conversión docx -> PDF del formato institucional de permisos. En Vercel
# no hay LibreOffice instalado, así que la conversión se manda a un
# microservicio aparte (Gotenberg, con LibreOffice adentro, desplegado en
# Render). En desarrollo local, sin GOTENBERG_URL, se sigue usando el
# LibreOffice instalado en la máquina (ver rrhh/utils.py).
GOTENBERG_URL = env.str('GOTENBERG_URL', default='')
GOTENBERG_USER = env.str('GOTENBERG_USER', default='')
GOTENBERG_PASSWORD = env.str('GOTENBERG_PASSWORD', default='')

# Notificación por correo cuando le toca firmar a alguien (ver
# rrhh.utils.notificar_turno_firma). Tres modos, en este orden de
# prioridad:
# 1. Microsoft Graph API (MS_GRAPH_CLIENT_ID configurado) -- necesario
#    para cuentas @muniolivar.cl: el tenant de Microsoft 365 tiene
#    "Security Defaults" activado, que bloquea SMTP básico (usuario +
#    contraseña) sin importar la config de la cuenta individual. Envía
#    autenticado con OAuth (client credentials), no por SMTP.
# 2. SMTP normal (EMAIL_HOST_USER configurado) -- sirve para Gmail u
#    otro proveedor sin esa restricción.
# 3. Consola (por defecto, sin nada configurado) -- desarrollo local:
#    los correos se imprimen en la consola en vez de enviarse de verdad.
if env.str('MS_GRAPH_CLIENT_ID', default=''):
    EMAIL_BACKEND = 'intranet.email_backend.MicrosoftGraphEmailBackend'
    MS_GRAPH_TENANT_ID = env.str('MS_GRAPH_TENANT_ID')
    MS_GRAPH_CLIENT_ID = env.str('MS_GRAPH_CLIENT_ID')
    MS_GRAPH_CLIENT_SECRET = env.str('MS_GRAPH_CLIENT_SECRET')
    MS_GRAPH_SENDER = env.str('MS_GRAPH_SENDER')
    DEFAULT_FROM_EMAIL = MS_GRAPH_SENDER
elif env.str('EMAIL_HOST_USER', default=''):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env.str('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = env.int('EMAIL_PORT', default=587)
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = env.str('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD', default='')
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'intranet@olivar.local'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'inicio'
LOGOUT_REDIRECT_URL = 'login'


# Endurecimiento de cookies/HTTPS. Solo tiene sentido cuando el sitio se
# sirve realmente por HTTPS (producción), por eso se activa junto con
# DEBUG=False y no en el entorno de desarrollo local.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    # HSTS_INCLUDE_SUBDOMAINS y HSTS_PRELOAD solo deben activarse cuando
    # TODO el dominio (y sus subdominios) esté 100% servido bajo HTTPS de
    # forma estable: son difíciles de revertir (preload en particular
    # queda cacheado en los navegadores por mucho tiempo).
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
