# Generated by Django 6.0.7 on 2026-07-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_add_secretaria_municipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='jefe',
            field=models.ForeignKey(blank=True, help_text='Jefatura directa de este departamento. Pendiente de completar con el organigrama oficial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_a_cargo', to='directorio.funcionario'),
        ),
    ]
