# Generated by Django 6.0.7 on 2026-07-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_departamento_jefe'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
