# Generated by Django 6.0.7 on 2026-07-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_funcionario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('funcionario', 'Funcionario'), ('jefe', 'Jefe'), ('director', 'Director')], max_length=150),
        ),
    ]
