# Generated by Django 6.0.7 on 2026-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('funcionario', 'Funcionario'), ('jefe', 'Jefe'), ('encargado', 'Encargado'), ('director', 'Director')], max_length=150),
        ),
    ]
