# Generated by Django 6.0.7 on 2026-07-30 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0007_alter_funcionario_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Se completa cuando la persona recibe su cuenta de acceso a la intranet. Al eliminar la cuenta de usuario, esta ficha de directorio se elimina con ella.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL),
        ),
    ]
