# Generated by Django 6.0.7 on 2026-07-31 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0008_alter_funcionario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, help_text="Jefe directo real de esta persona. Puede no coincidir con el jefe de su departamento (ej. unidades que dependen funcionalmente de otra dirección). Se usa para resolver quién firma como 'jefatura directa' en las solicitudes de permiso.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='directorio.funcionario'),
        ),
    ]
