# Generated by Django 6.0.7 on 2026-07-31 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0009_funcionario_jefe_directo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, help_text="Excepción manual: quién firma como 'jefatura directa' en las solicitudes de esta persona, si es distinto al jefe de su departamento (ej. unidades que dependen funcionalmente de otra dirección). Dejar vacío para usar el jefe del departamento.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='directorio.funcionario'),
        ),
    ]
