# Generated by Django 6.0.7 on 2026-07-28 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorio', '0003_add_secretaria_municipal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('cedula_identidad', 'Cédula de identidad'), ('contrato', 'Contrato / anexo'), ('titulo', 'Título o certificado de estudios'), ('certificado', 'Certificado'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(help_text='Ej: “Contrato 2026”, “Título Ingeniería”.', max_length=150)),
                ('archivo', models.FileField(upload_to='documentos_personales/%Y/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_personales', to='directorio.funcionario')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento personal',
                'verbose_name_plural': 'Documentos personales',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='FichaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('planta', 'Planta'), ('contrata', 'Contrata'), ('honorarios', 'Honorarios'), ('codigo_trabajo', 'Código del Trabajo')], max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('grado', models.CharField(blank=True, help_text='Grado EUS, si corresponde.', max_length=20)),
                ('jornada', models.CharField(blank=True, help_text='Ej: "44 horas semanales".', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_laboral', to='directorio.funcionario')),
            ],
            options={
                'verbose_name': 'Ficha laboral',
                'verbose_name_plural': 'Fichas laborales',
            },
        ),
        migrations.CreateModel(
            name='LicenciaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, help_text='Número de licencia, si viene en el documento.', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias', models.PositiveSmallIntegerField()),
                ('documento', models.FileField(blank=True, upload_to='licencias_medicas/%Y/%m/')),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('en_tramite', 'En trámite (Compin/Isapre)'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='registrada', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias_medicas', to='directorio.funcionario')),
            ],
            options={
                'verbose_name': 'Licencia médica',
                'verbose_name_plural': 'Licencias médicas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('administrativo', 'Día administrativo'), ('sin_goce', 'Permiso sin goce de sueldo'), ('otro', 'Otro')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias_solicitados', models.PositiveSmallIntegerField()),
                ('motivo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='directorio.funcionario')),
            ],
            options={
                'verbose_name': 'Solicitud de permiso',
                'verbose_name_plural': 'Solicitudes de permiso',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('archivo', models.FileField(upload_to='liquidaciones/%Y/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='directorio.funcionario')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liquidación de sueldo',
                'verbose_name_plural': 'Liquidaciones de sueldo',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('funcionario', 'anio', 'mes')},
            },
        ),
    ]
