# Generated by Django 6.0.7 on 2026-07-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopersonal',
            name='categoria',
            field=models.CharField(choices=[('cedula_identidad', 'Cédula de identidad'), ('contrato', 'Contrato / anexo'), ('titulo', 'Título o certificado de estudios'), ('certificado', 'Certificado (antigüedad, tipo de contrato, etc.)'), ('certificado_renta', 'Certificado de renta'), ('otro', 'Otro')], max_length=20),
        ),
    ]
