# Generated by Django 6.0.7 on 2026-07-31 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0009_funcionario_jefe_directo'),
        ('rrhh', '0002_alter_documentopersonal_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoUnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('jefa_personal', 'Jefa de Personal'), ('alcaldesa', 'Alcaldesa')], max_length=50, unique=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_unicos', to='directorio.funcionario')),
            ],
            options={
                'verbose_name': 'Cargo único',
                'verbose_name_plural': 'Cargos únicos',
            },
        ),
        migrations.CreateModel(
            name='FirmaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(help_text='1 a 4: orden en que debe firmarse.')),
                ('rol_firmante', models.CharField(choices=[('interesado', 'Interesado'), ('jefa_personal', 'Jefa de Personal'), ('jefatura_directa', 'Jefatura directa'), ('alcaldesa', 'Alcaldesa')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('firmado', 'Firmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('ip_firma', models.GenericIPAddressField(blank=True, null=True)),
                ('hash_documento', models.CharField(blank=True, help_text='sha256 del contenido de la solicitud al momento de firmar.', max_length=64)),
                ('comentario', models.TextField(blank=True)),
                ('funcionario_firmante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas', to='directorio.funcionario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='rrhh.solicitudpermiso')),
            ],
            options={
                'verbose_name': 'Firma de solicitud',
                'verbose_name_plural': 'Firmas de solicitud',
                'ordering': ['solicitud', 'orden'],
                'unique_together': {('solicitud', 'orden')},
            },
        ),
    ]
