# Generated by Django 6.0.7 on 2026-08-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_cargounico_firmasolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='comprobante_firma',
            field=models.FileField(blank=True, help_text='PDF de respaldo generado automáticamente al completarse las 4 firmas.', upload_to='comprobantes_firma/%Y/'),
        ),
    ]
