# Generated by Django 6.0.7 on 2026-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_solicitudpermiso_comprobante_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargounico',
            name='nombre',
            field=models.CharField(choices=[('alcaldesa', 'Alcaldesa')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='firmasolicitud',
            name='orden',
            field=models.PositiveSmallIntegerField(help_text='1 a 3: orden en que debe firmarse.'),
        ),
        migrations.AlterField(
            model_name='firmasolicitud',
            name='rol_firmante',
            field=models.CharField(choices=[('interesado', 'Interesado'), ('jefatura_directa', 'Jefatura directa'), ('alcaldesa', 'Alcaldesa')], max_length=20),
        ),
    ]
