# Generated by Django 6.0.7 on 2026-08-04 13:04
# Ajustado a mano: AddField con default callable + unique=True no genera
# valores únicos por fila en Postgres (evalúa el callable una sola vez),
# así que se agrega sin unique, se rellena fila por fila, y luego se
# aplica la restricción unique.

import rrhh.models
from django.db import migrations, models


def generar_codigos_existentes(apps, schema_editor):
    SolicitudPermiso = apps.get_model('rrhh', 'SolicitudPermiso')
    for solicitud in SolicitudPermiso.objects.all():
        solicitud.codigo_verificacion = rrhh.models.generar_codigo_verificacion()
        solicitud.save(update_fields=['codigo_verificacion'])


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_alter_cargounico_nombre_alter_firmasolicitud_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='codigo_verificacion',
            field=models.CharField(blank=True, default='', editable=False, help_text='Código público para verificar la autenticidad de esta solicitud sin iniciar sesión.', max_length=9),
        ),
        migrations.RunPython(generar_codigos_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='codigo_verificacion',
            field=models.CharField(default=rrhh.models.generar_codigo_verificacion, editable=False, help_text='Código público para verificar la autenticidad de esta solicitud sin iniciar sesión.', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='comprobante_firma',
            field=models.FileField(blank=True, help_text='PDF de respaldo generado automáticamente al completarse las 3 firmas.', upload_to='comprobantes_firma/%Y/'),
        ),
    ]
