# Generated by Django 6.0.7 on 2026-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_solicitudpermiso_codigo_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmasolicitud',
            name='hash_documento',
            field=models.CharField(blank=True, help_text='sha256 único de esta firma: liga el contenido de la solicitud a quién firmó, cuándo y desde qué IP. Distinto para cada una de las firmas, aunque compartan solicitud.', max_length=64),
        ),
    ]
