# Generated by Django 6.0.7 on 2026-08-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_alter_firmasolicitud_hash_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='documento_permiso',
            field=models.FileField(blank=True, help_text='PDF con el formato institucional (Solicitud de Permiso Administrativo y Feriado Legal), generado automáticamente al completarse las 3 firmas.', upload_to='documentos_permiso/%Y/'),
        ),
    ]
