# Generated by Django 6.0.7 on 2026-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_solicitudpermiso_documento_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmasolicitud',
            name='notificado_en',
            field=models.DateTimeField(blank=True, help_text='Cuándo se le avisó por correo a este firmante que le tocaba su turno (ver rrhh.utils.notificar_turno_firma) -- respaldo ante un reclamo de que el aviso nunca llegó. Queda vacío si el firmante no tiene correo cargado, o si el envío falló.', null=True),
        ),
    ]
