# Generated by Django 6.0.7 on 2026-07-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True, help_text='Si está activo, se le pide cambiar la clave apenas inicia sesión (se usa para las cuentas creadas con la clave genérica).'),
        ),
    ]
