# Generated by Django 6.0.7 on 2026-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('funcionario', 'Funcionario'), ('jefatura', 'Jefatura'), ('directivo', 'Directivo'), ('rrhh', 'RRHH'), ('admin', 'Administrador')], default='funcionario', max_length=20),
        ),
    ]
