# Generated by Django 6.0.7 on 2026-07-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('funcionario', 'Funcionario'), ('jefatura', 'Jefatura'), ('directivo', 'Directivo'), ('encargado', 'Encargado')], default='funcionario', max_length=20),
        ),
    ]
